services:
  webapp:
    image: ghcr.io/ullav-dev/ullav-dam-browser:latest
    container_name: ullav-dam-browser
    init: true
    env_file: .env.prod
    networks:
      - ullav-net
    restart: unless-stopped
    ports:
      - "3002:3002"

networks:
  ullav-net:
    external: true

